# Generated by Django 5.1 on 2024-08-27 00:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Expenses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expense_item', models.CharField(max_length=100)),
                ('purchased_date', models.DateTimeField(auto_now_add=True)),
                ('expense_amount', models.FloatField()),
                ('expense_category', models.CharField(choices=[('have', '')], max_length=10)),
                ('expense_payment_method', models.CharField(max_length=100)),
                ('expense_author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expense', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('income_date', models.DateTimeField(auto_now_add=True)),
                ('income_source', models.CharField(max_length=100)),
                ('income_amount', models.FloatField()),
                ('income_payment_method', models.CharField(max_length=100)),
                ('income_category', models.CharField(max_length=100)),
                ('income_author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='income', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
